### ISSUE TITLE
MIDDLEWARE_CLASSES setting is deprecated in Django 1.10

### ISSUE THREAD

**Issue by cryptogun** [nitely/Spirit#149]
```
MIDDLEWARE_CLASSES += [
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'spirit.core.middleware.XForwardedForMiddleware',
    'spirit.user.middleware.TimezoneMiddleware',
    'spirit.user.middleware.LastIPMiddleware',
    'spirit.user.middleware.LastSeenMiddleware',
    'spirit.user.middleware.ActiveUserMiddleware',
    'spirit.core.middleware.PrivateForumMiddleware',
]
```
If I change `MIDDLEWARE_CLASSES` above to `MIDDLEWARE` errors occur:
```
[2017-01-09 20:35:10 +0800] [9759] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/i/Desktop/env/lib/python3.5/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/home/i/Desktop/env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/i/Desktop/env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/i/Desktop/env/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/i/Desktop/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/i/Desktop/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/i/Desktop/env/lib/python3.5/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/home/i/Desktop/mysite/myapp/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/i/Desktop/env/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/i/Desktop/env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/home/i/Desktop/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
[2017-01-09 20:35:10 +0800] [9759] [INFO] Worker exiting (pid: 9759)
[2017-01-09 20:35:10 +0800] [9754] [INFO] Shutting down: Master
[2017-01-09 20:35:10 +0800] [9754] [INFO] Reason: Worker failed to boot.
```
So now I can't keep both `MIDDLEWARE_CLASSES` and `MIDDLEWARE`, and have to use `MIDDLEWARE_CLASSES` only.
Now I can see the forum and login page.

**Comment by nitely** [comment]
I just merged a fix for this one. Changing `MIDDLEWARE_CLASSES` to `MIDDLEWARE` should now work.

**Comment by cryptogun** [comment]
Feedback:
I commited out this exception,
```
raise ValueError(
            "djconfig.middleware.DjConfigMiddleware is required "
            "but it was not found in MIDDLEWARE_CLASSES"
        )
```
and find that:
`djconfig.middleware.DjConfigMiddleware` takes parameter `handler`
`spirit.core.middleware.PrivateForumMiddleware` still cause the error:
```
  File "/home/i/Desktop/
env/lib/python3.5/site-packages/django/core/handlers/base.py", line 83, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters
```
When I commit out `PrivateForumMiddleware`, `ActiveUserMiddleware` will cause that error. So does `LastSeenMiddleware`.

**Comment by nitely** [comment]
> spirit.core.middleware.PrivateForumMiddleware still cause the error

Are you on latest dev commit? [it should support new middleware](https://github.com/nitely/Spirit/blob/master/spirit/core/middleware.py#L22)

**Comment by cryptogun** [comment]
Sorry I forgot to include `--upgrade` when piping
`pip3 install git+https://github.com/nitely/Spirit.git --upgrade`
Now problem solved. Thank you.
