### ISSUE TITLE
Django(1.11.7) - django-hastack(2.6.1) version conflict

### ISSUE THREAD

**Issue by nordbit** [nitely/Spirit#204]
`Traceback (most recent call last):
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.11.7 (/srv/forum/lib/python3.6/site-packages), Requirement.parse('Django<1.11'), {'django-haystack'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/forum/bin/spirit", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/srv/forum/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.11.7 (/srv/forum/lib/python3.6/site-packages), Requirement.parse('Django<1.11'), {'django-haystack'})`

**Comment by nitely** [comment]
Thanks for reporting this. I just updated the deps.
