### ISSUE TITLE
Install project had a worng info

### ISSUE THREAD

**Issue by wangmingYu1212** [nitely/Spirit#224]
```python
    copying PIL\_util.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\__init__.py -> build\lib.win-amd64-3.6\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.editorconfig'
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    copying PIL\OleFileIO-README.md -> build\lib.win-amd64-3.6\PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ewaybot\AppData\Local\Temp\pip-build-isj62bhf\Pillow\setup.py", line 767, in <module>
        zip_safe=not debug_build(),
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\ewaybot\appdata\local\programs\python\python36\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\ewaybot\AppData\Local\Temp\pip-build-isj62bhf\Pillow\setup.py", line 516, in build_extensions
        (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

    ----------------------------------------
  Rolling back uninstall of Pillow
Command "c:\users\ewaybot\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ewaybot\\AppData\\Local\\Temp\\pip-build-isj62bhf\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ewaybot\AppData\Local\Temp\pip-9s_bs2cf-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ewaybot\AppData\Local\Temp\pip-build-isj62bhf\Pillow\
```

**Comment by nitely** [comment]
> ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

The error seems pretty clear. Try installing pillow before Spirit:

```
pip install pillow
```

If this still does not work you'll have to google how to install pillow on Windows. I'm closing this because I'm not a windows user, so I can't help you.
