### ISSUE TITLE
Unable to Send Email

### ISSUE THREAD

**Issue by YUX** [nitely/Spirit#298]
I've got this in prod_local.py
```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email host'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'name@example.com'
EMAIL_HOST_PASSWORD = 'password'
EMAIL_USE_SSL = True
```

then I create a `send_email_test.py`:
```
import os
from django.core.mail import send_mail

os.environ['DJANGO_SETTINGS_MODULE'] = 'mysite.settings.prod_local'

if __name__ == '__main__':   

    send_mail(
        'hello world',
        'welcome',
        'name@example.com',
        ['anothername@example.com'],
    )
```

the result is `send_email_test.py` works fine, which means the mail server functions as expected, but i can't send email in the forum like 'reset password' and 'send activation email'

please share some ideas to enlighten me
thanks

**Comment by nitely** [comment]
Hard to say without a traceback. You can edit settings/base.py and add `'file'` to the logger handlers to log to disk.

I should make it raise the error if `DEBUG=true` for easier debugging. Logging to disk is a good idea anyway.

**Comment by nitely** [comment]
btw, try setting the `DEFAULT_FROM_EMAIL` to your email address:

```
DEFAULT_FROM_EMAIL = 'noreply@example.com'
SERVER_EMAIL = DEFAULT_FROM_EMAIL
```

and check the SPAM folder...

**Comment by YUX** [comment]
thank you for the reply
I got these debug info in the console , not sure if that's relevant
```
web_1  | DEBUG 2020-12-22 09:41:52,986 selector_events 11 281472908177024 Using selector: EpollSelector
web_1  | DEBUG 2020-12-22 09:41:53,025 base 11 281472908177024 Exception while resolving variable 'parent' in template 'spirit/topic/active.html'.
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
web_1  |     current = current[bit]
web_1  | TypeError: 'NoneType' object is not subscriptable
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 837, in _resolve_lookup
web_1  |     current = getattr(current, bit)
web_1  | AttributeError: 'NoneType' object has no attribute 'parent'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 843, in _resolve_lookup
web_1  |     current = current[int(bit)]
web_1  | ValueError: invalid literal for int() with base 10: 'parent'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 848, in _resolve_lookup
web_1  |     raise VariableDoesNotExist("Failed lookup for key "
web_1  | django.template.base.VariableDoesNotExist: Failed lookup for key [parent] in None
web_1  | DEBUG 2020-12-22 09:41:53,030 base 11 281472908177024 Exception while resolving variable 'show_subcategory' in template 'spirit/topic/active.html'.
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
web_1  |     current = current[bit]
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
web_1  |     raise KeyError(key)
web_1  | KeyError: 'show_subcategory'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 835, in _resolve_lookup
web_1  |     if isinstance(current, BaseContext) and getattr(type(current), bit):
web_1  | AttributeError: type object 'RequestContext' has no attribute 'show_subcategory'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 843, in _resolve_lookup
web_1  |     current = current[int(bit)]
web_1  | ValueError: invalid literal for int() with base 10: 'show_subcategory'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 848, in _resolve_lookup
web_1  |     raise VariableDoesNotExist("Failed lookup for key "
web_1  | django.template.base.VariableDoesNotExist: Failed lookup for key [show_subcategory] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'uHI6s4mCtd7NO0DVjC3ZsI7kPalRRNBQLSMnVNjXfbE6CHSIhMJanQ2CCFGoh3Ii'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0xffff80fc9e50>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0xffff80f3a850>, 'LANGUAGES': [('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ky', 'Kyrgyz'), ('lt', 'Lithuanian'), ('pl', 'Polish'), ('pl-pl', 'Poland Polish'), ('ru', 'Russian'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('zh-hans', 'Simplified Chinese')], 'LANGUAGE_CODE': 'en', 'LANGUAGE_BIDI': False, 'MEDIA_URL': '/media/', 'STATIC_URL': '/static/', 'TIME_ZONE': 'UTC', 'request': <WSGIRequest: GET '/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0xffff80fc9eb0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'config': <djconfig.conf.Config object at 0xffff83522f10>}, {}, {'categories': <CategoryQuerySet [<Category: Category object (2)>]>, 'topics': <Page 1>, 'st_settings': {'ST_EXTENDED_FONT': False}}, {'block': <Block Node: content. Contents: [<TextNode: '\n  <div class="layout__ar'>, <django.template.loader_tags.IncludeNode object at 0xffff80ec25b0>, <TextNode: '\n\n    '>, <django.template.loader_tags.IncludeNode object at 0xffff80ec2580>, <TextNode: '\n\n    '>, <django.template.library.SimpleNode object at 0xffff80ec29d0>, <TextNode: '\n  </div>\n'>]>}, {}, {'forloop': {'parentloop': {}, 'counter0': 0, 'counter': 1, 'revcounter': 2, 'revcounter0': 1, 'first': True, 'last': False}, 't': <Topic: Topic object (2)>}]
web_1  | DEBUG 2020-12-22 09:41:53,031 base 11 281472908177024 Exception while resolving variable 'show_subcategory' in template 'spirit/topic/active.html'.
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
web_1  |     current = current[bit]
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
web_1  |     raise KeyError(key)
web_1  | KeyError: 'show_subcategory'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 835, in _resolve_lookup
web_1  |     if isinstance(current, BaseContext) and getattr(type(current), bit):
web_1  | AttributeError: type object 'RequestContext' has no attribute 'show_subcategory'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 843, in _resolve_lookup
web_1  |     current = current[int(bit)]
web_1  | ValueError: invalid literal for int() with base 10: 'show_subcategory'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 848, in _resolve_lookup
web_1  |     raise VariableDoesNotExist("Failed lookup for key "
web_1  | django.template.base.VariableDoesNotExist: Failed lookup for key [show_subcategory] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'uHI6s4mCtd7NO0DVjC3ZsI7kPalRRNBQLSMnVNjXfbE6CHSIhMJanQ2CCFGoh3Ii'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0xffff80fc9e50>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0xffff80f3a850>, 'LANGUAGES': [('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ky', 'Kyrgyz'), ('lt', 'Lithuanian'), ('pl', 'Polish'), ('pl-pl', 'Poland Polish'), ('ru', 'Russian'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('zh-hans', 'Simplified Chinese')], 'LANGUAGE_CODE': 'en', 'LANGUAGE_BIDI': False, 'MEDIA_URL': '/media/', 'STATIC_URL': '/static/', 'TIME_ZONE': 'UTC', 'request': <WSGIRequest: GET '/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0xffff80fc9eb0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'config': <djconfig.conf.Config object at 0xffff83522f10>}, {}, {'categories': <CategoryQuerySet [<Category: Category object (2)>]>, 'topics': <Page 1>, 'st_settings': {'ST_EXTENDED_FONT': False}}, {'block': <Block Node: content. Contents: [<TextNode: '\n  <div class="layout__ar'>, <django.template.loader_tags.IncludeNode object at 0xffff80ec25b0>, <TextNode: '\n\n    '>, <django.template.loader_tags.IncludeNode object at 0xffff80ec2580>, <TextNode: '\n\n    '>, <django.template.library.SimpleNode object at 0xffff80ec29d0>, <TextNode: '\n  </div>\n'>]>}, {}, {'forloop': {'parentloop': {}, 'counter0': 1, 'counter': 2, 'revcounter': 1, 'revcounter0': 0, 'first': False, 'last': True}, 't': <Topic: Topic object (1)>}]
web_1  | [pid: 11|app: 0|req: 1/1] 172.22.0.1 () {50 vars in 879 bytes} [Tue Dec 22 09:41:52 2020] GET / => generated 4702 bytes in 222 msecs (HTTP/1.1 200) 8 headers in 396 bytes (1 switches on core 0)
web_1  | DEBUG 2020-12-22 09:41:53,933 selector_events 13 281472908177024 Using selector: EpollSelector
web_1  | [pid: 13|app: 0|req: 1/2] 172.22.0.1 () {50 vars in 871 bytes} [Tue Dec 22 09:41:53 2020] GET /user/login/?next=/ => generated 3302 bytes in 173 msecs (HTTP/1.1 200) 10 headers in 508 bytes (1 switches on core 0)
web_1  | DEBUG 2020-12-22 09:41:55,865 base 11 281472860152176 Exception while resolving variable 'next' in template 'spirit/user/auth/activation_resend.html'.
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 829, in _resolve_lookup
web_1  |     current = current[bit]
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
web_1  |     raise KeyError(key)
web_1  | KeyError: 'next'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 835, in _resolve_lookup
web_1  |     if isinstance(current, BaseContext) and getattr(type(current), bit):
web_1  | AttributeError: type object 'RequestContext' has no attribute 'next'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 843, in _resolve_lookup
web_1  |     current = current[int(bit)]
web_1  | ValueError: invalid literal for int() with base 10: 'next'
web_1  |
web_1  | During handling of the above exception, another exception occurred:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 848, in _resolve_lookup
web_1  |     raise VariableDoesNotExist("Failed lookup for key "
web_1  | django.template.base.VariableDoesNotExist: Failed lookup for key [next] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'ZsCDFb49NKw0N3vRuJeuvfraNvJHSK6ogDGU8U1uzI3jBKKEsTUFqnmsA04ei0dQ'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0xffff80f8c070>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0xffff80e1c610>, 'LANGUAGES': [('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ky', 'Kyrgyz'), ('lt', 'Lithuanian'), ('pl', 'Polish'), ('pl-pl', 'Poland Polish'), ('ru', 'Russian'), ('sv', 'Swedish'), ('tr', 'Turkish'), ('zh-hans', 'Simplified Chinese')], 'LANGUAGE_CODE': 'en', 'LANGUAGE_BIDI': False, 'MEDIA_URL': '/media/', 'STATIC_URL': '/static/', 'TIME_ZONE': 'UTC', 'request': <WSGIRequest: GET '/user/resend-activation/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0xffff80f8c250>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'config': <djconfig.conf.Config object at 0xffff83522f10>}, {}, {'form': <ResendActivationForm bound=False, valid=Unknown, fields=(email)>, 'st_settings': {'ST_EXTENDED_FONT': False}}, {'block': <Block Node: content. Contents: [<TextNode: '\n  <div class="layout__ar'>, <django.templatetags.i18n.TranslateNode object at 0xffff80e24400>, <TextNode: '</h1>\n\n    <form action="'>, <django.template.defaulttags.CsrfTokenNode object at 0xffff80e24520>, <TextNode: '\n      '>, <django.template.loader_tags.IncludeNode object at 0xffff80e24640>, <TextNode: '\n\n      <input class="but'>, <django.templatetags.i18n.TranslateNode object at 0xffff80e24760>, <TextNode: '" />\n    </form>\n  </div>'>]>}, {}]
web_1  | [pid: 11|app: 0|req: 2/3] 172.22.0.1 () {50 vars in 900 bytes} [Tue Dec 22 09:41:55 2020] GET /user/resend-activation/ => generated 2663 bytes in 24 msecs (HTTP/1.1 200) 8 headers in 396 bytes (1 switches on core 1)
web_1  | [pid: 11|app: 0|req: 3/4] 172.22.0.1 () {56 vars in 1012 bytes} [Tue Dec 22 09:42:02 2020] POST /user/resend-activation/ => generated 0 bytes in 101 msecs (HTTP/1.1 302) 9 headers in 531 bytes (1 switches on core 0)
web_1  | DEBUG 2020-12-22 09:42:02,254 selector_events 9 281472908177024 Using selector: EpollSelector
web_1  | [pid: 9|app: 0|req: 1/5] 172.22.0.1 () {50 vars in 1115 bytes} [Tue Dec 22 09:42:02 2020] GET /user/login/ => generated 3767 bytes in 155 msecs (HTTP/1.1 200) 11 headers in 606 bytes (1 switches on core 0)

```

**Comment by nitely** [comment]
I don't see anything relevant in there. Here's an idea, try setting `EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'` so the email content gets printed to the console, and compare it with the `send_email_test.py` output.

**Comment by YUX** [comment]
I can't see the email content in the console. maybe the mail is not fired at all.

**Comment by YUX** [comment]
`send_email_test.py` output is normal as expected

**Comment by nitely** [comment]
mmh, try setting `ST_TASK_MANAGER = None`

**Comment by YUX** [comment]
still cannot see mail content in console

**Comment by nitely** [comment]
What's the `send_email_test.py` output? Does Spirit show the "email was sent" message in the UI?

**Comment by nitely** [comment]
> still cannot see mail content in console

Remember to restart the server after changing a setting.

**Comment by YUX** [comment]
the `send_email_test.py` output:
```
❯ python send_mail_test.py
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Subject: =?utf-8?b?5p2l6IeqTGVldHBhdOeahOa1i+ivlemCruS7tg==?=
From: name@example.com
To: name@gmail.com
Date: Tue, 22 Dec 2020 10:23:37 -0000
Message-ID: <160863261774.24824.2247791607941215906@mymac.local>

welcome 
-------------------------------------------------------------------------------
```

every time I change anything I use `python manage.py spiritinstall --settings=mysite.settings.dev_local` then `python manage.py runserver --settings=mysite.settings.dev_local` to reinstall and rerun

in the UI
```

Password reset successful

We've emailed you instructions for setting your password. You should be receiving them shortly.

If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.

```

**Comment by nitely** [comment]
So, I've tried adding this to the bottom of my prod.py file:

```python
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email host'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'name@example.com'
EMAIL_HOST_PASSWORD = 'password'
EMAIL_USE_SSL = True

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
```

and the email content is printed to the console:

```
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: User activation
From: webmaster@localhost
To: asd@asd.com
Date: Tue, 22 Dec 2020 10:26:47 -0000
Message-ID: <160863280752.108683.13462742588699492939@edev>


You're receiving this email because you registered at Spirit.

Please go to the following link to activate your account:

https://example.com/user/activation/1/eyJ1aWQiOiIxO0ZhbHNlIn0.1kresR.hAjNpqpmT9f5I9h7KukjyUjW1QXIPsv_GJ8doeS2JGk/

Thanks for using our site!
```

**Comment by nitely** [comment]
Can you paste your pro_local settings without any sensitive info?

**Comment by YUX** [comment]
```
from .prod import *


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

HUEY = {
    'huey_class': 'huey.SqliteHuey',
    'name': 'spirit',
    'filename': os.path.join(BASE_DIR, 'huey.sqlite3'),
    'immediate_use_memory': False,
    'immediate': False,
    'utc': True,
    'connection': {},
    'consumer': {
        'workers': os.cpu_count() * 2 + 1,
        'worker_type': 'thread',
        'initial_delay': 0.1,
        'backoff': 1.15,
        'max_delay': 10.0,
        'scheduler_interval': 1,
        'periodic': True,
        'check_worker_health': True,
        'health_check_interval': 1,
    }
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'email'
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_HOST = 'smtp server'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'email'
EMAIL_HOST_PASSWORD = 'psw'
EMAIL_USE_SSL = True



ADMINS = (('me', 'myemail'), )
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ST_ALLOWED_URL_PROTOCOLS = {'git', 'http', 'https', 'mailto'}
ST_MATH_JAX = True
ST_MENTIONS_PER_COMMENT = 5
ST_SEARCH_INDEX_UPDATE_HOURS = 1
ST_SEARCH_QUERY_MIN_LEN = 1
ST_SITE_URL = 'https://url/'
# ST_SITE_URL = 'http://127.0.0.1:8000/'
ST_TASK_MANAGER = 'huey'
ST_UPLOAD_FILE_ENABLED = False
ST_UPLOAD_IMAGE_ENABLED = True
ST_USER_LAST_SEEN_THRESHOLD_MINUTES = 180
ST_YT_PAGINATOR_PAGE_RANGE = 7

SECURE_HSTS_SECONDS = 31449600
# SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
ALLOWED_HOSTS = ['url', '0.0.0.0','localhost', '127.0.0.1']
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECRET_KEY = 'key'


```

**Comment by YUX** [comment]
I'll try remove anything and start from beginning.

**Comment by nitely** [comment]
I'm pretty sure this is your issue: `ST_TASK_MANAGER = 'huey'` you need to run the task manager to send the emails. If you set `ST_TASK_MANAGER = None` then it should work.

**Comment by YUX** [comment]
what's the best implement to run huey?
and does that require Redis?

**Comment by nitely** [comment]
I use `supervisord` to manage it and a systemd service to start it. You can just use a systemd service. You can [read the docs](https://spirit.readthedocs.io/en/latest/task_manager.html) if you haven't yet.

You can use SQLite as long as you run everything in a single machine (Spirit web server and the task manager). Your settings are ok if you want that. If you need to run the task manager in other machine and you have multiple Spirit web servers, then you need to use Redis. The docs explain this well.

**Comment by YUX** [comment]
thank you very much

I set task manager to None and it works

**Comment by YUX** [comment]
i really appreciate your time and kindness

**Comment by nitely** [comment]
No problem.

> I set task manager to None and it works

Beware of the caveats. The search indexation, and email notifications (user mentions/replies) won't work.

**Comment by YUX** [comment]
ok, I just figured out the huey and suddenly tons of email were received
