### ISSUE TITLE
ImportError: No module named Category

### ISSUE THREAD

**Issue by Boogymanx** [nitely/Spirit#39]
Hey guys! I've been looking into a few Django forums for an app I'm developing when I stumbled upon Spirit. I (and the other members of the team) love the way it looks, as well as the many functionalities it offers. However, after installing Spirit (both through pip install django-spirit and pip install -r requirements.txt), I can't run my migrations or my server because I'm getting an ImportError. This is the traceback: 
    Traceback (most recent call last):  
       File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
       File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 385, in      execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 354, in execute
       django.setup()
      File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
      File "/usr/local/lib/python3.4/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
      File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1448, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/usr/local/lib/python3.4/dist-packages/spirit/models/__init__.py", line 1, in <module>
    from category import Category
   ImportError: No module named 'category'

Do you have any clue what might be causing this? Many thanks in advance!

**Comment by Boogymanx** [comment]
So I fixed this by installing the future branch, however, now I can't seem to find the spirit User models for use with my User Profile. How should I replace a OneToOneField with django's User model? Sorry for the newbie questions, I really hope you guys can help me out!

**Comment by nitely** [comment]
Is this a new project? I mean... Do you have user's records in your
database?

You can extend (inherit) the spirit abstract user model, but it's not
mandatory. You should be able to make a onetoone rel as usual.

**Comment by Boogymanx** [comment]
Hmm, I changed my OneToOneField to     user = models.OneToOneField(spirit.settings.AUTH_USER_MODEL) and now I'm not getting any errors on migrations, however, it is asking me to delete anything related to auth.user after running migrations. Am I correct in assuming this would delete all my current users? It's not a huge issue really, I'd just have to define a new root user. It's not really a new project - there are several users for testing purposes but I can remake them. Thanks for your quick reply and sorry I didn't respond earlier, I was on my way home :)

**Comment by nitely** [comment]
Great. I'm not sure, I think it will just stop using your user table. You
are better off starting from scratch, migrating users is a pain.

2015-03-10 15:16 GMT-03:00 Boogymanx <notifications@github.com>:

**Comment by Boogymanx** [comment]
I accepted the delete in the migrations and I'm currently having a FieldError when trying to create a new superuser: django.core.exceptions.FieldError: Unknown field(s) (is_administrator, is_moderator, location, timezone)  (full traceback at the bottom) 

I think it's because I'm using your model as my base user and Django's not expecting those fields so I'll need to point Django's base user to your fields as well. Is it possible to point Django's base user to your models? Many thanks again for your swift reply :) 


    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
      File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
      File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
      File "/home/robbie/Bureaublad/Spirit-future/spirit/apps.py", line 14, in ready
    self.register_config()
      File "/home/robbie/Bureaublad/Spirit-future/spirit/apps.py", line 19, in register_config
    from spirit.forms.admin import BasicConfigForm
      File "/home/robbie/Bureaublad/Spirit-future/spirit/forms/admin.py", line 18, in <module>
    class UserEditForm(forms.ModelForm):
      File "/usr/local/lib/python3.4/dist-packages/django/forms/models.py", line 294, in __new__
    raise FieldError(message)
    django.core.exceptions.FieldError: Unknown field(s) (is_administrator, is_moderator, location, timezone) specified for User

**Comment by nitely** [comment]
Are you overwriting AUTH_USER_MODEL in your settings? If you are, don't do
that. It's that the createsuperuser command? I don't remeber if that
works... It should, though. I'll be able to try it myself in a couple of
hours.

> I think it's because I'm using your model as my base user and Django's
not expecting those fields so I'll need to point Django's base user to your
fields as well. Is it possible to point Django's base user to your models?

That's not the issue, you are no longer using the *default* django user
model. Spirit extends/swaps the django user model and adds a bunch of
fields to it [0].

[0]
https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#substituting-a-custom-user-model

2015-03-10 17:25 GMT-03:00 Boogymanx <notifications@github.com>:

**Comment by nitely** [comment]
Yep, `./manage.py createsuperuser` works fine. Your issue is elsewhere. You are probably overwritting `AUTH_USER_MODEL` in your `settings.py`, or maybe you are doing `from spirit.settings import *` at the top of your `settings.py`. Make sure to read the [example](https://github.com/nitely/Spirit/blob/future/example/project/settings/base.py) provided.

**Comment by Boogymanx** [comment]
For some reason I had from spirit import * instead of from spirit.settings import *. That fixed my User problem (I never defined an AUTH_USER_MODEL as I was just using Django's default. Not sure if this is good practice, for some reason I doubt it :p ). I have noticed however that the spirit admin forms don't show up in my admin panel (I also no longer have a User admin panel :p)  and I get an error when browsing to /forum/ (which is where I pointed spirit at). Traceback here: https://dpaste.de/KfxV

**Comment by nitely** [comment]
Did you add `url(r'^forum/', include('spirit.urls', namespace="spirit", app_name="spirit"))` to your urls.py?

There seems to be some apps missing in your `INSTALLED_APPS` (ie: haystack) and some middlewares as well, I can only guess you are overwritting settings instead of *extending* them.

**Comment by Boogymanx** [comment]
I did add that to my urls.py. I did make the newbie mistake of not adding the apps in your requirements.txt to my installed_apps, but I did that and am still getting the same error. What extra middleware do I need? I really am a Django noob (this is my first real project and I'm thinking of cleaning it up because I just learned there's a lot of best practices I didn't follow - past me really fucked present me). https://dpaste.de/KXfj is my current settings.py in case that helps.

**Comment by nitely** [comment]
Just [read the code](https://github.com/nitely/Spirit/blob/future/spirit/settings.py), you will find you are overwritting lots of things spirit needs to work properly. You should be [extending](https://github.com/nitely/Spirit/blob/future/example/project/settings/base.py) spirit settings instead. I don't know if that will solve the issue you are having but it is a good start.

**Comment by Boogymanx** [comment]
So I commented out all the duplicates and changed the = on INSTALLED_APPS, TEMPLATE_CONTEXT_PROCESSORS, and MIDDLEWARE_CLASSES in my settings (as well as removing pytz, whoosh and mistune)  and I'm still getting the same error :/ I've also tried installing only spirit in a fresh project with extended settings and the error persists. I'm not sure what I'm doing wrong, which is really frustrating. Could it be because I installed from the future branch instead of the master branch?

**Comment by nitely** [comment]
That's not it. The future branch is the stable one (yeah, I know...). Weird... did you tried the [example](https://github.com/nitely/Spirit/tree/future/example)? if that works, try changing the url to `forum/`.

**Comment by Boogymanx** [comment]
Sorry for not getting back to you earlier, I was in a meeting. When following the example, no manage.py gets created in the example folder and as such I can't continue with it. I'm going to be starting from scratch later today because I'm going to drastically change some models and I'm going to be removing all my currently installed apps and reinstalling only what's necessary, I'll hopefully manage to get it configured properly then. Thanks again for all the help!

**Comment by nitely** [comment]
The manage.py is already there, just clone the project and follow the steps.

2015-03-11 13:46 GMT-03:00 Boogymanx <notifications@github.com>:

**Comment by nitely** [comment]
Oh, it's missing in the `master` branch, use the `future` one.

**Comment by nitely** [comment]
Ah! I know what the problem is... I change the way urls get imported.

You should have `url(r'^forum/', include('spirit.urls')),` in your urls.py, not the other code I posted earlier, sorry.

**Comment by nitely** [comment]
I merged `future` into `master`.

Closing this due to inactivity, feel free to reopen it.
