### ISSUE TITLE
LookupError: No installed app with label 'spirit'.

### ISSUE THREAD

**Issue by nyxcharon** [nitely/Spirit#45]
Wanted to test setting up spirit in a fresh django app to mess around with it to see if it would work in an existing project.  

I get the following error when trying to migrate:  
```
root@boot2docker:~/testforum# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 337, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 371, in check
    all_issues = checks.run_checks(app_configs=app_configs, tags=tags)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 59, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/checks.py", line 12, in check_user_model
    cls = apps.get_model(settings.AUTH_USER_MODEL)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 150, in get_app_config
    raise LookupError("No installed app with label '%s'." % app_label)
LookupError: No installed app with label 'spirit'.
```

Steps I took (can reproduce multiple times):
```
#django-admin startproject testforum
#pip install django-spirit 
- Added url(r'^', include('spirit.urls')), to urls.py
- Added from spirit.settings import * to the top of  settings.py file
#./manage.py migrate
```

Running django 1.7 w/ python 2.7, here's the versions of everything else:
```
Django==1.7
Pillow==2.6.2
Whoosh==2.5.7
argparse==1.2.1
chardet==2.0.1
colorama==0.2.5
django-debug-toolbar==1.3.0
django-djconfig==0.3.2
django-haystack==2.3.1
django-infinite-scroll-pagination==0.1.3
django-spirit==0.2.1
html5lib==0.999
mistune==0.3.1
pytz==2015.2
requests==2.2.1
six==1.5.2
sqlparse==0.1.15
urllib3==1.7.1
wheel==0.24.0
wsgiref==0.1.2
```

I can clone the repository and get the example to work, so I am unsure as to why it wont work in a fresh app.  The only documentation I could find was the readme, so I would appreciate some help (or point me to any other documentation if it exist)

**Comment by nitely** [comment]
Are you extending the INSTALLED_APPS? ie: INSTALLED_APPS += (...) (notice
the plus sign)

**Comment by nyxcharon** [comment]
I was not. The documentation in the readme made it seem like that was not necessary as long as I had the import line in place. If I extend the installed apps like so:
```
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

INSTALLED_APPS+= ( 'spirit')
```

I get this error now when trying to migrate:
```
root@CSEESYSTEMS09:/testforum# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/spirit/apps.py", line 14, in ready
    self.register_config()
  File "/usr/local/lib/python2.7/dist-packages/spirit/apps.py", line 21, in register_config
    djconfig.register(BasicConfigForm)
  File "/usr/local/lib/python2.7/dist-packages/djconfig/registry.py", line 27, in register
    _check_backend()
  File "/usr/local/lib/python2.7/dist-packages/djconfig/registry.py", line 33, in _check_backend
    raise ValueError("LocMemCache requires DjConfigLocMemMiddleware "
ValueError: LocMemCache requires DjConfigLocMemMiddleware but it was not found in MIDDLEWARE_CLASSES
```

Here's the settings file for reference:
```
root@CSEESYSTEMS09:/testforum# cat testforum/settings.py
"""
Django settings for testforum project.

For more information on this file, see
https://docs.djangoproject.com/en/1.7/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.7/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from spirit.settings import *

BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.7/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd94y2e=53!#1g7@15xx^bnwn78o!0n65l12y6^x@__10$i9bka'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

INSTALLED_APPS+= ( 'spirit', )
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'testforum.urls'

WSGI_APPLICATION = 'testforum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.7/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.7/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.7/howto/static-files/

STATIC_URL = '/static/'
```

I apologize if this is all because of a simple error, I just tried to follow the steps in the readme.

**Comment by nitely** [comment]
Assignations such as `INSTALLED_APPS = ...` or `MIDDLEWARE_CLASSES = ...` will overwrite the Spirit settings. The [example's settings](https://github.com/nitely/Spirit/blob/master/example/project/settings/base.py) states that you should *extend* them (ie: `TUPLE_OR_LIST_CONSTANT += ...`, `DICT_CONSTANT.update({key: value, })`).

You *can* overwrite the settings, but that would defeat the `from spirit.settings import *` purpose. You can take a look at the [Spirit settings](https://github.com/nitely/Spirit/blob/master/spirit/settings.py) so you can add whatever middleware, app, etc your project requires that is not already there.

**Comment by nitely** [comment]
The settings you posted above, should look something like:

```python
"""
Django settings for testforum project.

For more information on this file, see
https://docs.djangoproject.com/en/1.7/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.7/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from spirit.settings import *

BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.7/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd94y2e=53!#1g7@15xx^bnwn78o!0n65l12y6^x@__10$i9bka'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS += (
    # 'django.missing.from.spirit.app',
    # 'myapp',
)

MIDDLEWARE_CLASSES += (
   #  'mymiddleware',
)

ROOT_URLCONF = 'testforum.urls'

WSGI_APPLICATION = 'testforum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.7/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.7/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.7/howto/static-files/

STATIC_URL = '/static/'
```

**Comment by nyxcharon** [comment]
Ah, I misunderstood your previous comment. I have spirit up and running now, thanks. I would like to note (in case others see this) that django 1.7.1 must be installed, using version 1.7 will result in a ```TypeError: __init__() got an unexpected keyword argument 'preserve_default' ```when migrating.

With that  said, thanks for the help, i'll close this now. If there's any documentation/examples/etc that needs to be written up for Spirit please let me know as I'd like to contribute to Spirit.

Thanks.
