### ISSUE TITLE
'Running the example application' on python3.4

### ISSUE THREAD

**Issue by rhodan** [nitely/Spirit#90]
Hi there
I have problem running the example application.
can someone help me with this?

$ git clone https://github.com/nitely/Spirit.git
$ cd Spirit
$ virtualenv venv
$ source ./venv/bin/activate
$ pip install .
$ cd example
$ python manage.py spiritinstall

and I get following error

```javascript
Operations to perform:
  Synchronize unmigrated apps: haystack, spirit_core, spirit_search, messages, spirit_category_admin, staticfiles, spirit_comment_flag_admin, spirit_topic_admin, moderate, spirit_admin, spirit_user_admin, spirit_user_auth
  Apply all migrations: spirit_comment_like, djconfig, sessions, spirit_user, admin, spirit_topic_unread, spirit_comment, spirit_comment_bookmark, spirit_topic_favorite, spirit_category, spirit_comment_flag, spirit_topic_poll, spirit_topic, spirit_topic_private, auth, spirit_comment_history, spirit_topic_notification, contenttypes, spirit_comment_poll
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states...
 DONE
  Applying contenttypes.0001_initial...
 OK
  Applying auth.0001_initial...
 OK
  Applying admin.0001_initial...
 OK
  Applying contenttypes.0002_remove_content_type_name...
 OK
  Applying auth.0002_alter_permission_name_max_length...
 OK
  Applying auth.0003_alter_user_email_max_length...
 OK
  Applying auth.0004_alter_user_username_opts...
 OK
  Applying auth.0005_alter_user_last_login_null...
 OK
  Applying auth.0006_require_contenttypes_0002...
 OK
  Applying djconfig.0001_initial...
 OK
  Applying sessions.0001_initial...
 OK
  Applying spirit_category.0001_initial...
 OK
  Applying spirit_category.0002_auto_20150728_0442...
 OK
  Applying spirit_category.0003_category_is_global...
 OK
  Applying spirit_topic.0001_initial...
 OK
  Applying spirit_comment.0001_initial...
 OK
  Applying spirit_comment.0002_auto_20150828_2003...
 OK
  Applying spirit_comment.0003_auto_20151115_0400...
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/anaconda3/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/anaconda3/lib/python3.4/site-packages/spirit/core/management/commands/spiritinstall.py", line 14, in handle
    call_command('migrate', stdout=self.stdout, stderr=self.stderr)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/anaconda3/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/anaconda3/lib/python3.4/site-packages/spirit/comment/migrations/0003_auto_20151115_0400.py", line 11, in render_comments
    from ...core.utils.markdown import Markdown
  File "/opt/anaconda3/lib/python3.4/site-packages/spirit/core/utils/markdown/__init__.py", line 3, in <module>
    from .markdown import Markdown
  File "/opt/anaconda3/lib/python3.4/site-packages/spirit/core/utils/markdown/markdown.py", line 8, in <module>
    from .inline import InlineLexer
  File "/opt/anaconda3/lib/python3.4/site-packages/spirit/core/utils/markdown/inline.py", line 40, in <module>
    class InlineLexer(mistune.InlineLexer):
  File "/opt/anaconda3/lib/python3.4/site-packages/spirit/core/utils/markdown/inline.py", line 42, in InlineLexer
    default_rules = copy.copy(mistune.InlineLexer.inline_html_rules)
AttributeError: type object 'InlineLexer' has no attribute 'inline_html_rules'

```

**Comment by nitely** [comment]
Run `pip show mistune` it should show mistune version 0.7.1. I suspect you have an older version though. `pip install .` should have installed the one Spirit requires.

**Comment by nitely** [comment]
Closing this. Feel free to re-open it.
