### ISSUE TITLE
Add Support for Django 1.9

### ISSUE THREAD

**Issue by darshit7** [nitely/Spirit#91]
from django.utils.datastructures import SortedDict
ImportError: cannot import name 'SortedDict'

**Comment by nitely** [comment]
Can you post the full traceback?

**Comment by darshit7** [comment]
(py_3.4_dj_1.9)darshitp@ParaUbuntuDev90:~/Downloads/Spirit-master/example$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/functools.py", line 448, in wrapper
    result = user_function(*args, **kwds)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by darshit7** [comment]
With runserver --noreload

(py_3.4_dj_1.9)darshitp@ParaUbuntuDev90:~/Downloads/Spirit-master/example$ python manage.py runserver --noreload
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/Django-1.9rc1-py3.4.egg/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/haystack/__init__.py", line 7, in <module>
    from haystack.utils import loading
  File "/opt/virtualenv/py_3.4_dj_1.9/lib/python3.4/site-packages/haystack/utils/loading.py", line 6, in <module>
    from django.utils.datastructures import SortedDict
ImportError: cannot import name 'SortedDict'
(py_3.4_dj_1.9)darshitp@ParaUbuntuDev90:~/Downloads/Spirit-master/example$

**Comment by nitely** [comment]
It seems [haystack does not supports Django 1.9 yet](https://github.com/django-haystack/django-haystack/pull/1277). I'll have to wait until they do to add support for it.

**Comment by nsomaru** [comment]
@nitely Haystack now supports Django 1.9 [according to this](https://github.com/django-haystack/django-haystack/pull/1277)

**Comment by nitely** [comment]
They are in like pre-alpha test. I'll wait for an official release.
